export const makes = ['Acura','Audi','BMW','Buick','Cadillac','Chevrolet','Chrysler','Dodge','Ford','GMC','Honda','Hyundai','INFINITI','Jaguar','Jeep','Kia','Lexus','Lincoln','Mazda','Mercedes-Benz','Mitsubishi','Nissan','Porsche','Scion','Subaru','Tesla','Toyota','Volkswagen','Volvo'];
export const models = {
	Acura: ['ILX','MDX','MDX Sport Hybrid','NSX','RDX','RLX','RLX Sport Hybrid','TLX'],
	Audi: ['A3','A3 Sportback e-tron','A4','A4 allroad','A5','A5 Sport','A6','A7','A8','allroad','Q3','Q5','Q7','R8','RS 3','RS 7','S3','S4','S5','S6','S7','S8','SQ5','TT'],
	BMW: ['2 Series','3 Series','4 Series','5 Series','6 Series','7 Series','i3','i8','M2','M3','M4','M5','M6','X1','X3','X4','X5','X5 M','X6','X6 M','Z4'],
	Buick: ['Cascada','Enclave','Encore','Envision','LaCrosse','Regal','Regal Sportback','Regal TourX','Verano'],
	Cadillac: ['ATS','ATS-V','CT6','CTS','CTS-V','ELR','Escalade','Escalade ESV','SRX','XT5','XTS'],
	Chevrolet: ['Bolt EV','Camaro','City Express','Colorado Crew Cab','Colorado Extended Cab','Corvette','Cruze','Cruze Limited','Equinox','Express 2500 Cargo','Express 2500 Passenger','Express 3500 Cargo','Express 3500 Passenger','Impala','Malibu','Malibu Limited','Silverado 1500 Crew Cab','Silverado 1500 Double Cab','Silverado 1500 Regular Cab','Silverado 2500 HD Crew Cab','Silverado 2500 HD Double Cab','Silverado 2500 HD Regular Cab','Silverado 3500 HD Crew Cab','Silverado 3500 HD Double Cab','Silverado 3500 HD Regular Cab','Sonic','Spark','Spark EV','SS','Suburban','Tahoe','Traverse','Trax','Volt'],
	Chrysler: ['200','300','Pacifica','Pacifica Hybrid','Town & Country'],
	Dodge: ['Challenger','Charger','Dart','Durango','Grand Caravan Passenger','Journey','Viper'],
	Ford: ['C-MAX Energi','C-MAX Hybrid','Edge','Escape','Expedition','Expedition EL','Expedition MAX','Explorer','F150 Regular Cab','F150 Super Cab','F150 SuperCrew Cab','F250 Super Duty Crew Cab','F250 Super Duty Regular Cab','F250 Super Duty Super Cab','F350 Super Duty Crew Cab','F350 Super Duty Regular Cab','F350 Super Duty Super Cab','F450 Super Duty Crew Cab','Fiesta','Flex','Focus','Fusion','Fusion Energi','Mustang','Taurus','Transit 150 Van','Transit 150 Wagon','Transit 250 Van','Transit 350 HD Van','Transit 350 Van','Transit 350 Wagon','Transit Connect Cargo','Transit Connect Passenger'],
	GMC: ['Acadia','Acadia Limited','Canyon Crew Cab','Canyon Extended Cab','Savana 2500 Cargo','Savana 2500 Passenger','Savana 3500 Cargo','Savana 3500 Passenger','Sierra 1500 Crew Cab','Sierra 1500 Double Cab','Sierra 1500 Regular Cab','Sierra 2500 HD Crew Cab','Sierra 2500 HD Double Cab','Sierra 2500 HD Regular Cab','Sierra 3500 HD Crew Cab','Sierra 3500 HD Double Cab','Sierra 3500 HD Regular Cab','Terrain','Yukon','Yukon XL'],
	Honda: ['Accord','Accord Hybrid','Civic','Civic Type R','Clarity Fuel Cell','CR-V','CR-Z','Fit','HR-V','Odyssey','Pilot','Ridgeline'],
	Hyundai: ['Accent','Azera','Elantra','Elantra GT','Genesis Coupe','Ioniq Electric','Ioniq Hybrid','Santa Fe','Santa Fe Sport','Sonata','Sonata Hybrid','Sonata Plug-in Hybrid','Tucson','Tucson Fuel Cell','Veloster'],
	INFINITI: ['Q50','Q60','Q70','QX30','QX50','QX60','QX70','QX80'],
	Jaguar: ['F-PACE','F-TYPE','XE','XF','XJ'],
	Jeep: ['Cherokee','Compass','Grand Cherokee','Patriot','Renegade','Wrangler','Wrangler Unlimited'],
	Kia: ['Cadenza','Forte','Forte Koup','Forte5','K900','Niro','Optima','Optima Hybrid','Optima Plug-in Hybrid','Rio','Sedona','Sorento','Soul','Soul EV','Sportage'],
	Lexus: ['CT','ES','GS','GX','IS','LC','LS','LX','NX','RC','RX'],
	Lincoln: ['Continental','MKC','MKS','MKT','MKX','MKZ','Navigator','Navigator L'],
	Mazda: ['CX-3','CX-5','CX-9','MAZDA3','MAZDA6','MX-5 Miata','MX-5 Miata RF'],
	'Mercedes-Benz': ['B-Class','C-Class','CLA','CLS','CLS-Class','E-Class','G-Class','GLA','GLC','GLC Coupe','GL-Class','GLE','GLE Coupe','GLS','Mercedes-AMG C-Class','Mercedes-AMG CLA','Mercedes-AMG CLS','Mercedes-AMG E-Class','Mercedes-AMG G-Class','Mercedes-AMG GLA','Mercedes-AMG GLC','Mercedes-AMG GLC Coupe','Mercedes-AMG GLE','Mercedes-AMG GLE Coupe','Mercedes-AMG GLS','Mercedes-AMG GT','Mercedes-AMG S-Class','Mercedes-AMG SL','Mercedes-AMG SLC','Mercedes-AMG SLK','Mercedes-Maybach S600','Mercedes-Maybach S-Class','Metris Cargo','Metris Passenger','Metris WORKER Cargo','Metris WORKER Passenger','S-Class','SL','SLC','SLK','Sprinter 2500 Cargo','Sprinter 2500 Crew','Sprinter 2500 Passenger','Sprinter 3500 Cargo','Sprinter 3500XD Cargo','Sprinter WORKER Cargo','Sprinter WORKER Passenger'],
	Mitsubishi: ['i-MiEV','Lancer','Mirage','Mirage G4','Outlander','Outlander Sport'],
	Nissan: ['370Z','Altima','Armada','Frontier Crew Cab','Frontier King Cab','GT-R','JUKE','LEAF','Maxima','Murano','NV1500 Cargo','NV200','NV2500 HD Cargo','NV3500 HD Cargo','NV3500 HD Passenger','Pathfinder','Quest','Rogue','Rogue Sport','Sentra','Titan Crew Cab','Titan King Cab','TITAN Single Cab','TITAN XD Crew Cab','TITAN XD King Cab','TITAN XD Single Cab','Versa','Versa Note'],
	Porsche: ['718 Boxster','718 Cayman','911','Boxster','Cayenne','Cayman','Macan','Panamera'],
	Scion: ['FR-S','iA','iM','tC'],
	Subaru: ['BRZ','Crosstrek','Forester','Impreza','Legacy','Outback','WRX'],
	Tesla: ['Model S','Model X'],
	Toyota: ['4Runner','86','Avalon','Avalon Hybrid','Camry','Camry Hybrid','C-HR','Corolla','Corolla iM','Highlander','Highlander Hybrid','Land Cruiser','Mirai','Prius','Prius c','Prius Prime','Prius v','RAV4','RAV4 Hybrid','Sequoia','Sienna','Tacoma Access Cab','Tacoma Double Cab','Tundra CrewMax','Tundra Double Cab','Tundra Regular Cab','Yaris','Yaris iA'],
	Volkswagon: ['Atlas','Beetle','CC','e-Golf','Eos','Golf','Golf Alltrack','Golf GTI','Golf R','Golf SportWagen','Jetta','Passat','Tiguan','Touareg'],
	Volvo: ['S60','S80','S90','V60','V90','XC40','XC60','XC70','XC90']
};
export const links = {
	Acura: 'http://cdn2.holytaco.com/wp-content/uploads/RN3.jpg',
	Audi: 'https://img.odometer.com/filter:scale/quill/f/9/b/3/6/d/f9b36db3/7cbbceda9d6c246a8f83e4aa78cbe3fe4686647b.png?mw=615',
	BMW: 'https://piximus.net/media/37765/redneck-car-hacks-that-everyone-needs-to-try-1.jpg',
	Buick: 'http://bigrednecktrucks.com/wp-content/uploads/2014/02/52f407d234795.jpg',
	Cadillac: 'https://i.kinja-img.com/gawker-media/image/upload/s--ribSHghe--/c_scale,f_auto,fl_progressive,q_80,w_800/18nc6noebjpc2jpg.jpg',
	Chevrolet: 'http://www.onedirt.com/files/2010/03/Picture-2.jpg',
	Chrysler: 'http://cdn.ebaumsworld.com/mediaFiles/picture/524127/1037240.jpg',
	Dodge: 'http://whitetrashrepairs.com/wp-content/uploads/2017/01/e2abac1eece7ab7e151cf96a0f9c28bd.jpg',
	Ford: 'https://i.pinimg.com/736x/7f/e2/db/7fe2db4618e75591df86507ae4f0df5b--truck-bed-car-pictures.jpg',
	GMC: 'http://i.dailymail.co.uk/i/pix/2014/02/05/article-2552152-1B36337A00000578-792_634x463.jpg',
	Honda: '',
	Hyundai: 'http://www.fullredneck.com/wp-content/uploads/2016/04/Redneck-Car-20.jpg',
	INFINITI: 'https://1funny.com/wp-content/uploads/2010/03/daily_picdump_640_70-e1269007416595.jpg',
	Jaguar: 'https://whyweprotest.net/attachments/hillbillyair-jpg.257602/',
	Jeep: 'http://www.stanceiseverything.com/wp-content/uploads/2011/03/jeep2.jpg',
	Kia: 'http://www.pirate4x4.com/forum/attachments/toyota-truck-4runner/435352-has-anyone-seen-rig-hillbilly-lowrider.jpg',
	Lexus: 'http://cdn0.wideopenspaces.com/wp-content/uploads/2016/11/screen-shot-2014-12-18-at-9.33.05-am.jpg',
	Lincoln: 'https://i.pinimg.com/originals/4d/de/01/4dde017ecf1613bf96188fd82c1bdc2e.jpg',
	Mazda: 'http://cdn.ebaumsworld.com/mediaFiles/picture/75397/981797.jpg',
	'Mercedes-Benz': 'http://www.fullredneck.com/wp-content/uploads/2015/06/46239.jpg',
	Mitsubishi: 'http://i.ytimg.com/vi/ULQ6196Tfds/0.jpg',
	Nissan: 'https://i.imgur.com/PWvXrUB.jpg?1',
	Porsche: 'https://i.pinimg.com/736x/2a/8c/93/2a8c939a3b087a1576c3a097ebffd9de--porsche--redneck.jpg',
	Scion: 'http://www.thedistractionnetwork.com/images/car-fails-382.jpg',
	Subaru: 'http://www.funcage.com/blog/wp-content/uploads/2013/11/Funny-Modified-Cars-014.jpg',
	Tesla: 'https://i.pinimg.com/564x/78/40/3a/78403a35e1e0c401189a590403729dd3--sun-solar-solar-power.jpg',
	Toyota: 'https://img.odometer.com/slides/3/1/0/1/5/3/3101538885/a68ee72672c1031d7d4a1662416dbe78c25bbe5b.jpeg',
	Volkswagon: 'https://i.kinja-img.com/gawker-media/image/upload/s--Fr122iGw--/c_scale,fl_progressive,q_80,w_800/187f2qbcdh5uxjpg.jpg',
	Volvo: 'https://www.oddee.com/wp-content/uploads/_media/imgs/articles2/a97266_g176_8-no-tire.jpg'

};
